name: Build React Vite Example

on:
  pull_requests:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project:
          - example
          - checkout-plugin
        node-version:
          - '20.x'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.project }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ matrix.project }}
        npm ci

    - name: Run ESLint (if present)
      run: |
        cd ${{ matrix.project }}
        if [ -f package.json ] && (grep -q '"lint"' package.json || grep -q '"eslint"' package.json); then
          npm run lint
        else
          echo "No lint script or eslint dependency found — skipping lint."
        fi

    - name: Type check with TypeScript (if present)
      run: |
        cd ${{ matrix.project }}
        if [ -f package.json ] && (grep -q '"typescript"' package.json || grep -q '"tsc"' package.json); then
          npx tsc --noEmit
        else
          echo "No TypeScript found — skipping type check."
        fi

    - name: Build project
      run: |
        cd ${{ matrix.project }}
        npm run build

    - name: Check build output
      run: |
        cd ${{ matrix.project }}
        # Accept common output dirs (dist, build, lib)
        if [ -d dist ]; then
          echo "Found dist/"
          ls -la dist/
          test -n "$(ls -A dist)" || (echo "dist is empty" && exit 1)
        elif [ -d build ]; then
          echo "Found build/"
          ls -la build/
          test -n "$(ls -A build)" || (echo "build is empty" && exit 1)
        elif [ -d lib ]; then
          echo "Found lib/"
          ls -la lib/
          test -n "$(ls -A lib)" || (echo "lib is empty" && exit 1)
        else
          echo "No build output directory (dist/build/lib) found." && exit 1
        fi
        echo "✅ Build completed successfully for ${{ matrix.project }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}-build
        path: |
          ${{ matrix.project }}/dist
          ${{ matrix.project }}/build
          ${{ matrix.project }}/lib
        if-no-files-found: warn
        retention-days: 7

    - name: Start preview server and test (example only)
      if: ${{ matrix.project == 'example' }}
      run: |
        cd example
        # Start preview server in background
        npm run preview &
        PREVIEW_PID=$!

        # Wait for server to start (adjust if required)
        sleep 5

        # Test if server is responding
        curl -f http://localhost:4173 || (kill $PREVIEW_PID || true; exit 1)

        # Kill preview server
        kill $PREVIEW_PID || true

        echo "✅ Preview server test passed for example!"
